CREATE DATABASE EdTech;
USE EdTech

CREATE TABLE Students ( 
    RA INTEGER UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    cpf VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL
);

CREATE USER 'AdmTech'@'localhost' IDENTIFIED BY '12345';
GRANT ALL PRIVILEGES ON EdTech.* TO 'AdmTech'@'localhost';
FLUSH PRIVILEGES;
